<?php
namespace xltxlm\ssoclient\SsoAdmin;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


class ThriftServerClient implements \xltxlm\ssoclient\SsoAdmin\ThriftServerIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function ssoadmininfo(\xltxlm\ssoclient\SsoAdmin\Ssoadminrequest $ssoadminrequest)
  {
    $this->send_ssoadmininfo($ssoadminrequest);
    return $this->recv_ssoadmininfo();
  }

  public function send_ssoadmininfo(\xltxlm\ssoclient\SsoAdmin\Ssoadminrequest $ssoadminrequest)
  {
    $args = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfo_args();
    $args->ssoadminrequest = $ssoadminrequest;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'ssoadmininfo', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('ssoadmininfo', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_ssoadmininfo()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\SsoAdmin\ThriftServer_ssoadmininfo_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfo_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("ssoadmininfo failed: unknown result");
  }

  public function ssoadmininfonull(\xltxlm\ssoclient\SsoAdmin\Ssoadmin $ssoadmin)
  {
    $this->send_ssoadmininfonull($ssoadmin);
    $this->recv_ssoadmininfonull();
  }

  public function send_ssoadmininfonull(\xltxlm\ssoclient\SsoAdmin\Ssoadmin $ssoadmin)
  {
    $args = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfonull_args();
    $args->ssoadmin = $ssoadmin;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'ssoadmininfonull', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('ssoadmininfonull', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_ssoadmininfonull()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\SsoAdmin\ThriftServer_ssoadmininfonull_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfonull_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    return;
  }

}


