<?php
namespace xltxlm\ssoclient\SsoAdmin;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface ThriftServerIf {
  /**
   * @param \xltxlm\ssoclient\SsoAdmin\ssoadminrequest $ssoadminrequest
   * @return \xltxlm\ssoclient\SsoAdmin\ssoadmin[]
   */
  public function ssoadmininfo(\xltxlm\ssoclient\SsoAdmin\Ssoadminrequest $ssoadminrequest);
  /**
   * @param \xltxlm\ssoclient\SsoAdmin\ssoadmin $ssoadmin
   */
  public function ssoadmininfonull(\xltxlm\ssoclient\SsoAdmin\Ssoadmin $ssoadmin);
}


class ThriftServerClient implements \xltxlm\ssoclient\SsoAdmin\ThriftServerIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function ssoadmininfo(\xltxlm\ssoclient\SsoAdmin\Ssoadminrequest $ssoadminrequest)
  {
    $this->send_ssoadmininfo($ssoadminrequest);
    return $this->recv_ssoadmininfo();
  }

  public function send_ssoadmininfo(\xltxlm\ssoclient\SsoAdmin\Ssoadminrequest $ssoadminrequest)
  {
    $args = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfo_args();
    $args->ssoadminrequest = $ssoadminrequest;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'ssoadmininfo', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('ssoadmininfo', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_ssoadmininfo()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\SsoAdmin\ThriftServer_ssoadmininfo_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfo_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("ssoadmininfo failed: unknown result");
  }

  public function ssoadmininfonull(\xltxlm\ssoclient\SsoAdmin\Ssoadmin $ssoadmin)
  {
    $this->send_ssoadmininfonull($ssoadmin);
    $this->recv_ssoadmininfonull();
  }

  public function send_ssoadmininfonull(\xltxlm\ssoclient\SsoAdmin\Ssoadmin $ssoadmin)
  {
    $args = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfonull_args();
    $args->ssoadmin = $ssoadmin;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'ssoadmininfonull', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('ssoadmininfonull', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_ssoadmininfonull()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\SsoAdmin\ThriftServer_ssoadmininfonull_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfonull_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    return;
  }

}


// HELPER FUNCTIONS AND STRUCTURES

class ThriftServer_ssoadmininfo_args {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\SsoAdmin\ssoadminrequest
   */
  public $ssoadminrequest = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'ssoadminrequest',
          'type' => TType::STRUCT,
          'class' => '\kuaigeng\sso\Thrift\SsoAdmin\ssoadminrequest',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['ssoadminrequest'])) {
        $this->ssoadminrequest = $vals['ssoadminrequest'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_ssoadmininfo_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->ssoadminrequest = new \xltxlm\ssoclient\SsoAdmin\ssoadminrequest();
            $xfer += $this->ssoadminrequest->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_ssoadmininfo_args');
    if ($this->ssoadminrequest !== null) {
      if (!is_object($this->ssoadminrequest)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('ssoadminrequest', TType::STRUCT, 1);
      $xfer += $this->ssoadminrequest->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_ssoadmininfo_result {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\SsoAdmin\ssoadmin[]
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\kuaigeng\sso\Thrift\SsoAdmin\ssoadmin',
            ),
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_ssoadmininfo_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::LST) {
            $this->success = array();
            $_size0 = 0;
            $_etype3 = 0;
            $xfer += $input->readListBegin($_etype3, $_size0);
            for ($_i4 = 0; $_i4 < $_size0; ++$_i4)
            {
              $elem5 = null;
              $elem5 = new \xltxlm\ssoclient\SsoAdmin\ssoadmin();
              $xfer += $elem5->read($input);
              $this->success []= $elem5;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_ssoadmininfo_result');
    if ($this->success !== null) {
      if (!is_array($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('success', TType::LST, 0);
      {
        $output->writeListBegin(TType::STRUCT, count($this->success));
        {
          foreach ($this->success as $iter6)
          {
            $xfer += $iter6->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_ssoadmininfonull_args {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\SsoAdmin\ssoadmin
   */
  public $ssoadmin = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'ssoadmin',
          'type' => TType::STRUCT,
          'class' => '\kuaigeng\sso\Thrift\SsoAdmin\ssoadmin',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['ssoadmin'])) {
        $this->ssoadmin = $vals['ssoadmin'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_ssoadmininfonull_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->ssoadmin = new \xltxlm\ssoclient\SsoAdmin\ssoadmin();
            $xfer += $this->ssoadmin->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_ssoadmininfonull_args');
    if ($this->ssoadmin !== null) {
      if (!is_object($this->ssoadmin)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('ssoadmin', TType::STRUCT, 1);
      $xfer += $this->ssoadmin->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_ssoadmininfonull_result {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'ThriftServer_ssoadmininfonull_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_ssoadmininfonull_result');
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServerProcessor {
  protected $handler_ = null;
  public function __construct($handler) {
    $this->handler_ = $handler;
  }

  public function process($input, $output) {
    $rseqid = 0;
    $fname = null;
    $mtype = 0;

    $input->readMessageBegin($fname, $mtype, $rseqid);
    $methodname = 'process_'.$fname;
    if (!method_exists($this, $methodname)) {
      $input->skip(TType::STRUCT);
      $input->readMessageEnd();
      $x = new TApplicationException('Function '.$fname.' not implemented.', TApplicationException::UNKNOWN_METHOD);
      $output->writeMessageBegin($fname, TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $this->$methodname($rseqid, $input, $output);
    return true;
  }

  protected function process_ssoadmininfo($seqid, $input, $output) {
    $args = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfo_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfo_result();
    $result->success = $this->handler_->ssoadmininfo($args->ssoadminrequest);
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'ssoadmininfo', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('ssoadmininfo', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
  protected function process_ssoadmininfonull($seqid, $input, $output) {
    $args = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfonull_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \xltxlm\ssoclient\SsoAdmin\ThriftServer_ssoadmininfonull_result();
    $this->handler_->ssoadmininfonull($args->ssoadmin);
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'ssoadmininfonull', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('ssoadmininfonull', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
}

