<?php
namespace xltxlm\ssoclient\SsoAdmin;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


class ThriftServer_ssoadmininfo_args {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\SsoAdmin\ssoadminrequest
   */
  public $ssoadminrequest = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'ssoadminrequest',
          'type' => TType::STRUCT,
          'class' => '\kuaigeng\sso\Thrift\SsoAdmin\ssoadminrequest',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['ssoadminrequest'])) {
        $this->ssoadminrequest = $vals['ssoadminrequest'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_ssoadmininfo_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->ssoadminrequest = new \xltxlm\ssoclient\SsoAdmin\ssoadminrequest();
            $xfer += $this->ssoadminrequest->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_ssoadmininfo_args');
    if ($this->ssoadminrequest !== null) {
      if (!is_object($this->ssoadminrequest)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('ssoadminrequest', TType::STRUCT, 1);
      $xfer += $this->ssoadminrequest->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

