<?php
namespace xltxlm\ssoclient\SsoAdmin;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface ThriftServerIf {
  /**
   * @param \xltxlm\ssoclient\SsoAdmin\ssoadminrequest $ssoadminrequest
   * @return \xltxlm\ssoclient\SsoAdmin\ssoadmin[]
   */
  public function ssoadmininfo(\xltxlm\ssoclient\SsoAdmin\Ssoadminrequest $ssoadminrequest);
  /**
   * @param \xltxlm\ssoclient\SsoAdmin\ssoadmin $ssoadmin
   */
  public function ssoadmininfonull(\xltxlm\ssoclient\SsoAdmin\Ssoadmin $ssoadmin);
}


