<?php
namespace xltxlm\ssoclient\Sso_userlock;

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


final class elasticsearch {
  const WEI_SUO_YIN = 1;
  const YI_SUO_YIN = 2;
  static public $__names = array(
    1 => 'WEI_SUO_YIN',
    2 => 'YI_SUO_YIN',
  );
}

