<?php
namespace xltxlm\ssoclient\Sso_userlock;

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


final class status {
  const DAI_DING = 1;
  const TONG_GUO = 2;
  const BU_TONG_GUO = 3;
  static public $__names = array(
    1 => 'DAI_DING',
    2 => 'TONG_GUO',
    3 => 'BU_TONG_GUO',
  );
}

