<?php
namespace xltxlm\ssoclient\Sso_userlock;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface ThriftServerIf {
  /**
   * @param \xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock
   * @return int
   */
  public function Sso_userlockInsert(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock);
  /**
   * @param \xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock
   * @return \xltxlm\ssoclient\Sso_userlock\SsoUserlock Structs are the basic complex data structures. They are comprised of fields
   * which each have an integer identifier, a type, a symbolic name, and an
   * optional default value.
   * 
   * Fields can be declared "optional", which ensures they will not be included
   * in the serialized output if they aren't set.  Note that this requires some
   * manual management in some languages.
   * 
   */
  public function Sso_userlockSelectOne(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock);
  /**
   * @param \xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock
   * @return \xltxlm\ssoclient\Sso_userlock\SsoUserlock[]
   */
  public function Sso_userlockSelectAll(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock);
}


class ThriftServerClient implements \xltxlm\ssoclient\Sso_userlock\ThriftServerIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function Sso_userlockInsert(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $this->send_Sso_userlockInsert($SsoUserlock);
    return $this->recv_Sso_userlockInsert();
  }

  public function send_Sso_userlockInsert(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $args = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockInsert_args();
    $args->SsoUserlock = $SsoUserlock;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'Sso_userlockInsert', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('Sso_userlockInsert', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_Sso_userlockInsert()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\Sso_userlock\ThriftServer_Sso_userlockInsert_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockInsert_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("Sso_userlockInsert failed: unknown result");
  }

  public function Sso_userlockSelectOne(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $this->send_Sso_userlockSelectOne($SsoUserlock);
    return $this->recv_Sso_userlockSelectOne();
  }

  public function send_Sso_userlockSelectOne(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $args = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectOne_args();
    $args->SsoUserlock = $SsoUserlock;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'Sso_userlockSelectOne', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('Sso_userlockSelectOne', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_Sso_userlockSelectOne()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\Sso_userlock\ThriftServer_Sso_userlockSelectOne_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectOne_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("Sso_userlockSelectOne failed: unknown result");
  }

  public function Sso_userlockSelectAll(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $this->send_Sso_userlockSelectAll($SsoUserlock);
    return $this->recv_Sso_userlockSelectAll();
  }

  public function send_Sso_userlockSelectAll(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $args = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectAll_args();
    $args->SsoUserlock = $SsoUserlock;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'Sso_userlockSelectAll', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('Sso_userlockSelectAll', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_Sso_userlockSelectAll()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\Sso_userlock\ThriftServer_Sso_userlockSelectAll_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectAll_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("Sso_userlockSelectAll failed: unknown result");
  }

}


// HELPER FUNCTIONS AND STRUCTURES

class ThriftServer_Sso_userlockInsert_args {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso_userlock\SsoUserlock
   */
  public $SsoUserlock = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'SsoUserlock',
          'type' => TType::STRUCT,
          'class' => '\kuaigeng\sso\Thrift\Sso_userlock\SsoUserlock',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['SsoUserlock'])) {
        $this->SsoUserlock = $vals['SsoUserlock'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_Sso_userlockInsert_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->SsoUserlock = new \xltxlm\ssoclient\Sso_userlock\SsoUserlock();
            $xfer += $this->SsoUserlock->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_Sso_userlockInsert_args');
    if ($this->SsoUserlock !== null) {
      if (!is_object($this->SsoUserlock)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('SsoUserlock', TType::STRUCT, 1);
      $xfer += $this->SsoUserlock->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_Sso_userlockInsert_result {
  static $_TSPEC;

  /**
   * @var int
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_Sso_userlockInsert_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->success);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_Sso_userlockInsert_result');
    if ($this->success !== null) {
      $xfer += $output->writeFieldBegin('success', TType::I32, 0);
      $xfer += $output->writeI32($this->success);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_Sso_userlockSelectOne_args {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso_userlock\SsoUserlock
   */
  public $SsoUserlock = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'SsoUserlock',
          'type' => TType::STRUCT,
          'class' => '\kuaigeng\sso\Thrift\Sso_userlock\SsoUserlock',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['SsoUserlock'])) {
        $this->SsoUserlock = $vals['SsoUserlock'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_Sso_userlockSelectOne_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->SsoUserlock = new \xltxlm\ssoclient\Sso_userlock\SsoUserlock();
            $xfer += $this->SsoUserlock->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_Sso_userlockSelectOne_args');
    if ($this->SsoUserlock !== null) {
      if (!is_object($this->SsoUserlock)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('SsoUserlock', TType::STRUCT, 1);
      $xfer += $this->SsoUserlock->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_Sso_userlockSelectOne_result {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso_userlock\SsoUserlock
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::STRUCT,
          'class' => '\kuaigeng\sso\Thrift\Sso_userlock\SsoUserlock',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_Sso_userlockSelectOne_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::STRUCT) {
            $this->success = new \xltxlm\ssoclient\Sso_userlock\SsoUserlock();
            $xfer += $this->success->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_Sso_userlockSelectOne_result');
    if ($this->success !== null) {
      if (!is_object($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('success', TType::STRUCT, 0);
      $xfer += $this->success->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_Sso_userlockSelectAll_args {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso_userlock\SsoUserlock
   */
  public $SsoUserlock = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'SsoUserlock',
          'type' => TType::STRUCT,
          'class' => '\kuaigeng\sso\Thrift\Sso_userlock\SsoUserlock',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['SsoUserlock'])) {
        $this->SsoUserlock = $vals['SsoUserlock'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_Sso_userlockSelectAll_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->SsoUserlock = new \xltxlm\ssoclient\Sso_userlock\SsoUserlock();
            $xfer += $this->SsoUserlock->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_Sso_userlockSelectAll_args');
    if ($this->SsoUserlock !== null) {
      if (!is_object($this->SsoUserlock)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('SsoUserlock', TType::STRUCT, 1);
      $xfer += $this->SsoUserlock->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_Sso_userlockSelectAll_result {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso_userlock\SsoUserlock[]
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\kuaigeng\sso\Thrift\Sso_userlock\SsoUserlock',
            ),
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_Sso_userlockSelectAll_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::LST) {
            $this->success = array();
            $_size0 = 0;
            $_etype3 = 0;
            $xfer += $input->readListBegin($_etype3, $_size0);
            for ($_i4 = 0; $_i4 < $_size0; ++$_i4)
            {
              $elem5 = null;
              $elem5 = new \xltxlm\ssoclient\Sso_userlock\SsoUserlock();
              $xfer += $elem5->read($input);
              $this->success []= $elem5;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_Sso_userlockSelectAll_result');
    if ($this->success !== null) {
      if (!is_array($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('success', TType::LST, 0);
      {
        $output->writeListBegin(TType::STRUCT, count($this->success));
        {
          foreach ($this->success as $iter6)
          {
            $xfer += $iter6->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServerProcessor {
  protected $handler_ = null;
  public function __construct($handler) {
    $this->handler_ = $handler;
  }

  public function process($input, $output) {
    $rseqid = 0;
    $fname = null;
    $mtype = 0;

    $input->readMessageBegin($fname, $mtype, $rseqid);
    $methodname = 'process_'.$fname;
    if (!method_exists($this, $methodname)) {
      $input->skip(TType::STRUCT);
      $input->readMessageEnd();
      $x = new TApplicationException('Function '.$fname.' not implemented.', TApplicationException::UNKNOWN_METHOD);
      $output->writeMessageBegin($fname, TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $this->$methodname($rseqid, $input, $output);
    return true;
  }

  protected function process_Sso_userlockInsert($seqid, $input, $output) {
    $args = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockInsert_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockInsert_result();
    $result->success = $this->handler_->Sso_userlockInsert($args->SsoUserlock);
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'Sso_userlockInsert', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('Sso_userlockInsert', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
  protected function process_Sso_userlockSelectOne($seqid, $input, $output) {
    $args = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectOne_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectOne_result();
    $result->success = $this->handler_->Sso_userlockSelectOne($args->SsoUserlock);
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'Sso_userlockSelectOne', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('Sso_userlockSelectOne', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
  protected function process_Sso_userlockSelectAll($seqid, $input, $output) {
    $args = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectAll_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectAll_result();
    $result->success = $this->handler_->Sso_userlockSelectAll($args->SsoUserlock);
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'Sso_userlockSelectAll', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('Sso_userlockSelectAll', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
}

