<?php
namespace xltxlm\ssoclient\Sso_userlock;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


class ThriftServerClient implements \xltxlm\ssoclient\Sso_userlock\ThriftServerIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function Sso_userlockInsert(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $this->send_Sso_userlockInsert($SsoUserlock);
    return $this->recv_Sso_userlockInsert();
  }

  public function send_Sso_userlockInsert(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $args = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockInsert_args();
    $args->SsoUserlock = $SsoUserlock;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'Sso_userlockInsert', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('Sso_userlockInsert', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_Sso_userlockInsert()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\Sso_userlock\ThriftServer_Sso_userlockInsert_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockInsert_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("Sso_userlockInsert failed: unknown result");
  }

  public function Sso_userlockSelectOne(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $this->send_Sso_userlockSelectOne($SsoUserlock);
    return $this->recv_Sso_userlockSelectOne();
  }

  public function send_Sso_userlockSelectOne(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $args = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectOne_args();
    $args->SsoUserlock = $SsoUserlock;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'Sso_userlockSelectOne', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('Sso_userlockSelectOne', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_Sso_userlockSelectOne()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\Sso_userlock\ThriftServer_Sso_userlockSelectOne_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectOne_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("Sso_userlockSelectOne failed: unknown result");
  }

  public function Sso_userlockSelectAll(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $this->send_Sso_userlockSelectAll($SsoUserlock);
    return $this->recv_Sso_userlockSelectAll();
  }

  public function send_Sso_userlockSelectAll(\xltxlm\ssoclient\Sso_userlock\SsoUserlock $SsoUserlock)
  {
    $args = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectAll_args();
    $args->SsoUserlock = $SsoUserlock;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'Sso_userlockSelectAll', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('Sso_userlockSelectAll', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_Sso_userlockSelectAll()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\kuaigeng\sso\Thrift\Sso_userlock\ThriftServer_Sso_userlockSelectAll_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\Sso_userlock\ThriftServer_Sso_userlockSelectAll_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("Sso_userlockSelectAll failed: unknown result");
  }

}


