<?php
namespace xltxlm\ssoclient\Sso_userlock;

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


/**
 * You can define enums, which are just 32 bit integers. Values are optional
 * and start at 1 if not supplied, C style again.
 */
final class lockoption {
  const DENG_YU = 1;
  const BU_DENG_YU = 2;
  const BAO_HAN = 3;
  const BU_ZAI_LIE_BIAO_ZHONG = 4;
  static public $__names = array(
    1 => 'DENG_YU',
    2 => 'BU_DENG_YU',
    3 => 'BAO_HAN',
    4 => 'BU_ZAI_LIE_BIAO_ZHONG',
  );
}

final class status {
  const DAI_DING = 1;
  const TONG_GUO = 2;
  const BU_TONG_GUO = 3;
  static public $__names = array(
    1 => 'DAI_DING',
    2 => 'TONG_GUO',
    3 => 'BU_TONG_GUO',
  );
}

final class elasticsearch {
  const WEI_SUO_YIN = 1;
  const YI_SUO_YIN = 2;
  static public $__names = array(
    1 => 'WEI_SUO_YIN',
    2 => 'YI_SUO_YIN',
  );
}

/**
 * Structs are the basic complex data structures. They are comprised of fields
 * which each have an integer identifier, a type, a symbolic name, and an
 * optional default value.
 * 
 * Fields can be declared "optional", which ensures they will not be included
 * in the serialized output if they aren't set.  Note that this requires some
 * manual management in some languages.
 */
class SsoUserlock {
  static $_TSPEC;

  /**
   * @var string
   */
  public $id = null;
  /**
   * @var string
   */
  public $ctroller_class = null;
  /**
   * @var string
   */
  public $user = null;
  /**
   * @var string
   */
  public $field = null;
  /**
   * @var string
   */
  public $lockoption = null;
  /**
   * @var string
   */
  public $lockvalue = null;
  /**
   * @var string
   */
  public $username = null;
  /**
   * @var string
   */
  public $status = null;
  /**
   * @var string
   */
  public $add_time = null;
  /**
   * @var string
   */
  public $update_time = null;
  /**
   * @var string
   */
  public $elasticsearch = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'id',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'ctroller_class',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'user',
          'type' => TType::STRING,
          ),
        4 => array(
          'var' => 'field',
          'type' => TType::STRING,
          ),
        5 => array(
          'var' => 'lockoption',
          'type' => TType::STRING,
          ),
        6 => array(
          'var' => 'lockvalue',
          'type' => TType::STRING,
          ),
        7 => array(
          'var' => 'username',
          'type' => TType::STRING,
          ),
        8 => array(
          'var' => 'status',
          'type' => TType::STRING,
          ),
        9 => array(
          'var' => 'add_time',
          'type' => TType::STRING,
          ),
        10 => array(
          'var' => 'update_time',
          'type' => TType::STRING,
          ),
        11 => array(
          'var' => 'elasticsearch',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['id'])) {
        $this->id = $vals['id'];
      }
      if (isset($vals['ctroller_class'])) {
        $this->ctroller_class = $vals['ctroller_class'];
      }
      if (isset($vals['user'])) {
        $this->user = $vals['user'];
      }
      if (isset($vals['field'])) {
        $this->field = $vals['field'];
      }
      if (isset($vals['lockoption'])) {
        $this->lockoption = $vals['lockoption'];
      }
      if (isset($vals['lockvalue'])) {
        $this->lockvalue = $vals['lockvalue'];
      }
      if (isset($vals['username'])) {
        $this->username = $vals['username'];
      }
      if (isset($vals['status'])) {
        $this->status = $vals['status'];
      }
      if (isset($vals['add_time'])) {
        $this->add_time = $vals['add_time'];
      }
      if (isset($vals['update_time'])) {
        $this->update_time = $vals['update_time'];
      }
      if (isset($vals['elasticsearch'])) {
        $this->elasticsearch = $vals['elasticsearch'];
      }
    }
  }

  public function getName() {
    return 'SsoUserlock';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->id);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->ctroller_class);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->user);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->field);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->lockoption);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 6:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->lockvalue);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 7:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->username);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 8:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->status);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 9:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->add_time);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 10:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->update_time);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 11:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->elasticsearch);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('SsoUserlock');
    if ($this->id !== null) {
      $xfer += $output->writeFieldBegin('id', TType::STRING, 1);
      $xfer += $output->writeString($this->id);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->ctroller_class !== null) {
      $xfer += $output->writeFieldBegin('ctroller_class', TType::STRING, 2);
      $xfer += $output->writeString($this->ctroller_class);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->user !== null) {
      $xfer += $output->writeFieldBegin('user', TType::STRING, 3);
      $xfer += $output->writeString($this->user);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->field !== null) {
      $xfer += $output->writeFieldBegin('field', TType::STRING, 4);
      $xfer += $output->writeString($this->field);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->lockoption !== null) {
      $xfer += $output->writeFieldBegin('lockoption', TType::STRING, 5);
      $xfer += $output->writeString($this->lockoption);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->lockvalue !== null) {
      $xfer += $output->writeFieldBegin('lockvalue', TType::STRING, 6);
      $xfer += $output->writeString($this->lockvalue);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->username !== null) {
      $xfer += $output->writeFieldBegin('username', TType::STRING, 7);
      $xfer += $output->writeString($this->username);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->status !== null) {
      $xfer += $output->writeFieldBegin('status', TType::STRING, 8);
      $xfer += $output->writeString($this->status);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->add_time !== null) {
      $xfer += $output->writeFieldBegin('add_time', TType::STRING, 9);
      $xfer += $output->writeString($this->add_time);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->update_time !== null) {
      $xfer += $output->writeFieldBegin('update_time', TType::STRING, 10);
      $xfer += $output->writeString($this->update_time);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->elasticsearch !== null) {
      $xfer += $output->writeFieldBegin('elasticsearch', TType::STRING, 11);
      $xfer += $output->writeString($this->elasticsearch);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}


