<?php
namespace xltxlm\ssoclient\Sso;

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


/**
 * You can define enums, which are just 32 bit integers. Values are optional
 * and start at 1 if not supplied, C style again.
 */
final class access {
  const CAO_ZUO = 1;
  const ZHI_DU = 2;
  const WU_QUAN_XIAN = 3;
  static public $__names = array(
    1 => 'CAO_ZUO',
    2 => 'ZHI_DU',
    3 => 'WU_QUAN_XIAN',
  );
}

