<?php
namespace xltxlm\ssoclient\Sso;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface ThriftServerIf {
  /**
   * @param \xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser
   * @return int
   */
  public function SsoctrolleruserInsert(\xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser);
  /**
   * @param \xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser
   * @return \xltxlm\ssoclient\Sso\Ssoctrolleruser Structs are the basic complex data structures. They are comprised of fields
   * which each have an integer identifier, a type, a symbolic name, and an
   * optional default value.
   * 
   * Fields can be declared "optional", which ensures they will not be included
   * in the serialized output if they aren't set.  Note that this requires some
   * manual management in some languages.
   * 
   */
  public function SsoctrolleruserSelectOne(\xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser);
  /**
   * @param \xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser
   * @return \xltxlm\ssoclient\Sso\Ssoctrolleruser[]
   */
  public function SsoctrolleruserSelectAll(\xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser);
}


class ThriftServerClient implements \xltxlm\ssoclient\Sso\ThriftServerIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function SsoctrolleruserInsert(\xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser)
  {
    $this->send_SsoctrolleruserInsert($Ssoctrolleruser);
    return $this->recv_SsoctrolleruserInsert();
  }

  public function send_SsoctrolleruserInsert(\xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser)
  {
    $args = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserInsert_args();
    $args->Ssoctrolleruser = $Ssoctrolleruser;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'SsoctrolleruserInsert', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('SsoctrolleruserInsert', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_SsoctrolleruserInsert()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\xltxlm\allinone\Thrift\Ssoctrolleruser\ThriftServer_SsoctrolleruserInsert_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserInsert_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("SsoctrolleruserInsert failed: unknown result");
  }

  public function SsoctrolleruserSelectOne(\xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser)
  {
    $this->send_SsoctrolleruserSelectOne($Ssoctrolleruser);
    return $this->recv_SsoctrolleruserSelectOne();
  }

  public function send_SsoctrolleruserSelectOne(\xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser)
  {
    $args = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserSelectOne_args();
    $args->Ssoctrolleruser = $Ssoctrolleruser;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'SsoctrolleruserSelectOne', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('SsoctrolleruserSelectOne', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_SsoctrolleruserSelectOne()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\xltxlm\allinone\Thrift\Ssoctrolleruser\ThriftServer_SsoctrolleruserSelectOne_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserSelectOne_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("SsoctrolleruserSelectOne failed: unknown result");
  }

  public function SsoctrolleruserSelectAll(\xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser)
  {
    $this->send_SsoctrolleruserSelectAll($Ssoctrolleruser);
    return $this->recv_SsoctrolleruserSelectAll();
  }

  public function send_SsoctrolleruserSelectAll(\xltxlm\ssoclient\Sso\Ssoctrolleruser $Ssoctrolleruser)
  {
    $args = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserSelectAll_args();
    $args->Ssoctrolleruser = $Ssoctrolleruser;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'SsoctrolleruserSelectAll', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('SsoctrolleruserSelectAll', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_SsoctrolleruserSelectAll()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\xltxlm\allinone\Thrift\Ssoctrolleruser\ThriftServer_SsoctrolleruserSelectAll_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserSelectAll_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("SsoctrolleruserSelectAll failed: unknown result");
  }

}


// HELPER FUNCTIONS AND STRUCTURES

class ThriftServer_SsoctrolleruserInsert_args {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso\Ssoctrolleruser
   */
  public $Ssoctrolleruser = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'Ssoctrolleruser',
          'type' => TType::STRUCT,
          'class' => '\xltxlm\allinone\Thrift\Ssoctrolleruser\Ssoctrolleruser',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['Ssoctrolleruser'])) {
        $this->Ssoctrolleruser = $vals['Ssoctrolleruser'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_SsoctrolleruserInsert_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->Ssoctrolleruser = new \xltxlm\ssoclient\Sso\Ssoctrolleruser();
            $xfer += $this->Ssoctrolleruser->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_SsoctrolleruserInsert_args');
    if ($this->Ssoctrolleruser !== null) {
      if (!is_object($this->Ssoctrolleruser)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('Ssoctrolleruser', TType::STRUCT, 1);
      $xfer += $this->Ssoctrolleruser->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_SsoctrolleruserInsert_result {
  static $_TSPEC;

  /**
   * @var int
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_SsoctrolleruserInsert_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->success);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_SsoctrolleruserInsert_result');
    if ($this->success !== null) {
      $xfer += $output->writeFieldBegin('success', TType::I32, 0);
      $xfer += $output->writeI32($this->success);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_SsoctrolleruserSelectOne_args {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso\Ssoctrolleruser
   */
  public $Ssoctrolleruser = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'Ssoctrolleruser',
          'type' => TType::STRUCT,
          'class' => '\xltxlm\allinone\Thrift\Ssoctrolleruser\Ssoctrolleruser',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['Ssoctrolleruser'])) {
        $this->Ssoctrolleruser = $vals['Ssoctrolleruser'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_SsoctrolleruserSelectOne_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->Ssoctrolleruser = new \xltxlm\ssoclient\Sso\Ssoctrolleruser();
            $xfer += $this->Ssoctrolleruser->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_SsoctrolleruserSelectOne_args');
    if ($this->Ssoctrolleruser !== null) {
      if (!is_object($this->Ssoctrolleruser)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('Ssoctrolleruser', TType::STRUCT, 1);
      $xfer += $this->Ssoctrolleruser->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_SsoctrolleruserSelectOne_result {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso\Ssoctrolleruser
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::STRUCT,
          'class' => '\xltxlm\allinone\Thrift\Ssoctrolleruser\Ssoctrolleruser',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_SsoctrolleruserSelectOne_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::STRUCT) {
            $this->success = new \xltxlm\ssoclient\Sso\Ssoctrolleruser();
            $xfer += $this->success->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_SsoctrolleruserSelectOne_result');
    if ($this->success !== null) {
      if (!is_object($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('success', TType::STRUCT, 0);
      $xfer += $this->success->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_SsoctrolleruserSelectAll_args {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso\Ssoctrolleruser
   */
  public $Ssoctrolleruser = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'Ssoctrolleruser',
          'type' => TType::STRUCT,
          'class' => '\xltxlm\allinone\Thrift\Ssoctrolleruser\Ssoctrolleruser',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['Ssoctrolleruser'])) {
        $this->Ssoctrolleruser = $vals['Ssoctrolleruser'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_SsoctrolleruserSelectAll_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->Ssoctrolleruser = new \xltxlm\ssoclient\Sso\Ssoctrolleruser();
            $xfer += $this->Ssoctrolleruser->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_SsoctrolleruserSelectAll_args');
    if ($this->Ssoctrolleruser !== null) {
      if (!is_object($this->Ssoctrolleruser)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('Ssoctrolleruser', TType::STRUCT, 1);
      $xfer += $this->Ssoctrolleruser->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServer_SsoctrolleruserSelectAll_result {
  static $_TSPEC;

  /**
   * @var \xltxlm\ssoclient\Sso\Ssoctrolleruser[]
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\xltxlm\allinone\Thrift\Ssoctrolleruser\Ssoctrolleruser',
            ),
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'ThriftServer_SsoctrolleruserSelectAll_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::LST) {
            $this->success = array();
            $_size0 = 0;
            $_etype3 = 0;
            $xfer += $input->readListBegin($_etype3, $_size0);
            for ($_i4 = 0; $_i4 < $_size0; ++$_i4)
            {
              $elem5 = null;
              $elem5 = new \xltxlm\ssoclient\Sso\Ssoctrolleruser();
              $xfer += $elem5->read($input);
              $this->success []= $elem5;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ThriftServer_SsoctrolleruserSelectAll_result');
    if ($this->success !== null) {
      if (!is_array($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('success', TType::LST, 0);
      {
        $output->writeListBegin(TType::STRUCT, count($this->success));
        {
          foreach ($this->success as $iter6)
          {
            $xfer += $iter6->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ThriftServerProcessor {
  protected $handler_ = null;
  public function __construct($handler) {
    $this->handler_ = $handler;
  }

  public function process($input, $output) {
    $rseqid = 0;
    $fname = null;
    $mtype = 0;

    $input->readMessageBegin($fname, $mtype, $rseqid);
    $methodname = 'process_'.$fname;
    if (!method_exists($this, $methodname)) {
      $input->skip(TType::STRUCT);
      $input->readMessageEnd();
      $x = new TApplicationException('Function '.$fname.' not implemented.', TApplicationException::UNKNOWN_METHOD);
      $output->writeMessageBegin($fname, TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $this->$methodname($rseqid, $input, $output);
    return true;
  }

  protected function process_SsoctrolleruserInsert($seqid, $input, $output) {
    $args = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserInsert_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserInsert_result();
    $result->success = $this->handler_->SsoctrolleruserInsert($args->Ssoctrolleruser);
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'SsoctrolleruserInsert', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('SsoctrolleruserInsert', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
  protected function process_SsoctrolleruserSelectOne($seqid, $input, $output) {
    $args = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserSelectOne_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserSelectOne_result();
    $result->success = $this->handler_->SsoctrolleruserSelectOne($args->Ssoctrolleruser);
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'SsoctrolleruserSelectOne', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('SsoctrolleruserSelectOne', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
  protected function process_SsoctrolleruserSelectAll($seqid, $input, $output) {
    $args = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserSelectAll_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \xltxlm\ssoclient\Sso\ThriftServer_SsoctrolleruserSelectAll_result();
    $result->success = $this->handler_->SsoctrolleruserSelectAll($args->Ssoctrolleruser);
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'SsoctrolleruserSelectAll', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('SsoctrolleruserSelectAll', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
}

